name: build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
            arch: x86_64
    steps:
    - uses: actions/checkout@v3
    - name: install apt packages
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq build-essential gpg
    - name: build
      run: ./build.sh ${{matrix.target}} ${{matrix.arch}} && mv -v releases/bash releases/bash-${{matrix.target}}-${{matrix.arch}}
      shell: bash
    - uses: actions/upload-artifact@v3  
      with:
        name: bash-${{matrix.target}}-${{matrix.arch}}
        path: releases/bash-${{matrix.target}}-${{matrix.arch}}
  release:
    needs:
      - build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: generate changelog
        run: ./changelog.sh
      - uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: make executable
        run: chmod +x artifacts/*/*
      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*/*
          body_path: NOTES.txt
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
